import {
  Activity,
  BookOpen,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CheckCircle2,
  CircleUserRound,
  Coins,
  Dumbbell,
  Lock,
  Map,
  Menu,
  Plus,
  Shield,
  Swords,
  UserRound,
  UsersRound,
} from 'lucide-react';

export const Icons = {
  activity: Activity,
  account: UserRound,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  check: CheckCircle2,
  characters: UsersRound,
  codex: BookOpen,
  coins: Coins,
  combat: Swords,
  endurance: Dumbbell,
  lock: Lock,
  map: Map,
  menu: Menu,
  plus: Plus,
  profile: CircleUserRound,
  shield: Shield,
};
